### ISSUE TITLE
b站闪退

### ISSUE THREAD

**Issue by jerryc127** [cinit/WSAPatch#11]
b站闪退

打开软件 闪了一下就退出
不知道为什么

------------
顺带问下 怎么完全卸载 [WSAPatch](https://github.com/cinit/WSAPatch)

**Comment by cinit** [comment]
WSAPatch 就两个 dll, 把它们删掉就行。至于 WSA 内应用闪退以及如何卸载 WSA 的问题请移步 WSA 寻求帮助。
