### ISSUE TITLE
WSA launched after installing update KB5020030

### ISSUE THREAD

**Issue by MrKristofere** [cinit/WSAPatch#2]
With your patch, WSA can only be launched after installing update KB5020030. Analyze what changes the update makes, maybe you can find out what other files need to be added so that you can run without installing this update.
P.S. you can move the WSA window if you hold the cursor near the "minimize" button.

**Comment by cinit** [comment]
Extracting and analyzing the ~400MB KB5020030 update will be too many works. Since KB5020030 is just a optional OS Builds 19045.2311 update, installing it will not take much effort. I will update the README file and clarify this system requirement.
