### ISSUE TITLE
Is it possible use this patch or try to make this patch work on Windows 10 ARM (Snapdragon 8c Compute Platforms)

### ISSUE THREAD

**Issue by MustardChef** [cinit/WSAPatch#22]
First of all, thank you for all the work done on this project.

My question is whether or not it is possible to patch WSA to make it work on Windows 10 ARM.

**Comment by cinit** [comment]
If your Windows 10 ARM is able to run WSL2, then it should be able to run WSA.

**Comment by MustardChef** [comment]
Using the same .dlls? The reason this question was asked as because I was unsure if the same patched .dlls in releases could be used

**Comment by cinit** [comment]
> Using the same patched .dlls? The reason this question was asked as because I was unsure if the same patched .dlls in releases could be used for arm64 WSA builds as I was suspecting that the dlls were only for x64

You need to compile WsaPatch.dll for arm64 and find an icu.dll from arm64 Windows 11 and patch it yourself.

**Comment by MustardChef** [comment]
Thank you for clarifying!

**Comment by YT-Advanced** [comment]
@MustardChef Did you tested your workflow dll file on ARM64, I need some information before adding DLL to the [WSA-Script](https://github.com/YT-Advanced/WSA-Script/) repo

**Comment by MustardChef** [comment]
> @MustardChef Did you tested your workflow dll file on Windows 10 ARM64, I need some information before adding DLL to the [WSA-Script](https://github.com/YT-Advanced/WSA-Script/) repo

If you use the same WSAPatch DLLs to try to run WSA on Windows 10 arm64, it will not work. According to the answer here, you need to compile the DLLs for arm64

**Comment by YT-Advanced** [comment]
> If you use the same WSAPatch DLLs to try to run WSA on Windows 10 arm64, it will not work. According to the answer here, you need to compile the DLLs for arm64

Yes, I meant the ARM64 DLL build from [your repos](https://github.com/MustardChef/WSAPatch/actions/runs/4087308678)

**Comment by MustardChef** [comment]
> > If you use the same WSAPatch DLLs to try to run WSA on Windows 10 arm64, it will not work. According to the answer here, you need to compile the DLLs for arm64
> 
> I meant the ARM64 DLL build from [your repos](https://github.com/MustardChef/WSAPatch/actions/runs/4087308678)

Well, I need someone who is able to test them. So its not confirmed that they work, but they should theoretically work.
