### ISSUE TITLE
可以让windows server 2022运行wsa吗？

### ISSUE THREAD

**Issue by milkdog114514** [cinit/WSAPatch#24]
winver 20348.1487

**Comment by cinit** [comment]
你试试 CI https://github.com/cinit/WSAPatch/actions/runs/3975324739 的 WsaPatch.dll, (icu.dll 从 release 里下，它是注入入口点)

**Comment by milkdog114514** [comment]
我试试看

**Comment by milkdog114514** [comment]
> 你试试 CI https://github.com/cinit/WSAPatch/actions/runs/3975324739 的 WsaPatch.dll, (icu.dll 从 release 里下，它是注入入口点)

我卡在安装这步了，想办法整了好久没整明白。似乎是缺少一个叫“Microsoft.classicAppInstaller_8wekyb3d8bbwe”的软件

**Comment by milkdog114514** [comment]
> > 你试试 CI https://github.com/cinit/WSAPatch/actions/runs/3975324739 的 WsaPatch.dll, (icu.dll 从 release 里下，它是注入入口点)
> 
> 我卡在安装这步了，想办法整了好久没整明白。似乎是缺少一个叫“Microsoft.classicAppInstaller_8wekyb3d8bbwe”的软件

没事了，我把那段xml删了就可以装了

**Comment by milkdog114514** [comment]
删除AppxManifest.xml内包含Microsoft.classicAppInstaller_8wekyb3d8bbwe整行删除
