### ISSUE TITLE
WSA crashed at startup in windows 10 v19045.2364

### ISSUE THREAD

**Issue by mehraanakbarii** [cinit/WSAPatch#3]
Hello 
basically I dont understand step one : 

Get WSA appx zip. You can do this by following instructions in https://github.com/LSPosed/MagiskOnWSALocal (You need to "build" this yourself with your local WSL2).

and because of that I got WSA MSIX from **https://store.rg-adguard.net**  and then extract it with 7zip and install it 
I copied your provided patched dlls to WSAClient dir but WSA does not work and crashed at startup

can you upload and share your own built WSA appx zip file ? I can not "build" it myself with my local WSL2 

thanks for your effort

**Comment by cinit** [comment]
Which version of WSA are you using?
You can find the version of your WSA in the `AppxManifest.xml` file. That's something like
```xml
<Identity Name="MicrosoftCorporationII.WindowsSubsystemForAndroid" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Version="2210.40000.7.0" ProcessorArchitecture="x64" />
```

**Comment by mehraanakbarii** [comment]
2210.40000.7.0

**Comment by cinit** [comment]
Try run `Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml` in PowerShell (run as admin) in your WSA installation directory and check whether there is any error message. If any error exists, follow the instruction (run `Get-AppPackageLog -ActivityID <UUID>` as prompted) to view the detail error logs.

**Comment by mehraanakbarii** [comment]
still does not work the setting window is crashing please share your WSA dir as .zip

**Comment by mehraanakbarii** [comment]
Thanks issue solved
