### ISSUE TITLE
WSAPatch has broken in v2304 of WSA

### ISSUE THREAD

**Issue by MustardChef** [cinit/WSAPatch#33]
@cinit WSAPatch is no longer working with WSA v2304.40000.3.0 and higher, giving the following error: 
![image](https://github.com/cinit/WSAPatch/assets/68516357/040761b1-94d1-4054-8454-7462c8350e9f)
Please can you have a look at the issue on hand.

Many thanks,
MustardChef

**Comment by MustardChef** [comment]
I have corresponded with @cinit and have been  told that they are busy with their studies and will work on the patch in the coming weeks after they have some free time. I would revert back to 2303.40000.5.0 in the meantime by either getting WSA from here https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2303.40000.5.0

**Comment by Ansh4011** [comment]
@MustardChef Hi mate. Apparently `WSA_2305.40000.3.0_x64` seems to work smooth enough for me. I am running window 10 ltsc (21h2). 
How did I build it? Downloaded the corresponding release from [WSABuilds](https://github.com/MustardChef/WSABuilds) which is by default meant for win11. Downloaded patches from [WSAPatch](https://github.com/cinit/WSAPatch) and placed them at the respective place, then edited `appxmanifest.xml` and ran `run.bat`.
At this stage, I did encounter an issue where the `resource language` and `resource uap` nodes in `appxmanifest.xml` got repeated twice after running `run.bat` and then `install.ps1` would throw error, so simply edited out the extra instances, don't know what triggered that error but it's surely something related to `run.bat`, happened twice. 
Later, also changed the location of the folder in which resides `userdata.vhdx`, and works completely fine as well.
Rest, it simply works good. Pretty stable for daily usage imho. Note it was a fresh install, no amazon store and had gapps. Cpu is i5-3230m if that matters.
Lastly, thanks a lot @MustardChef and @cinit for the awesome work, you didn't leave a single reason for me to switch to windows 11, I still feel windows 10 is much better and has better ui, not to mention it's customizable enough.
![wsa](https://github.com/cinit/WSAPatch/assets/84930340/03e3a3f9-5311-4904-9168-fed855ae7c06)

**Comment by YT-Advanced** [comment]
@Ansh4011 Can you explain more about your way please. I can't understand this line
> Later, also changed the location of the folder in which resides userdata.vhdx, and works completely fine as well.

**Comment by Ansh4011** [comment]
> @Ansh4011 Can you explain more about your way please. I can't understand this line
> 
> > Later, also changed the location of the folder in which resides userdata.vhdx, and works completely fine as well.

I was referring to step 3 of this guide on MustardChef's repo `WSABuild`. https://github.com/MustardChef/WSABuilds/blob/master/Guides/MoveToExtDrive.md#step-3-moving-the-appdata-vhdx--data-from-your-windows-drive-c-to-the-desired-partitiondrive

Also, tbh there's no my way, I just followed the installation/patching steps and it happened to work for me.

**Comment by YT-Advanced** [comment]
So you mean we must install WSA at other drive then use mklink to make symlink for working with Windows 10 ?

**Comment by YT-Advanced** [comment]
@Ansh4011 So you mean we must install WSA at other drive then use mklink to make symlink for working with Windows 10 ?

**Comment by YT-Advanced** [comment]
@Ansh4011 And can you please tell me which DLL version you are using for patching ?

**Comment by Ansh4011** [comment]
> @Ansh4011 So you mean we must install WSA at other drive then use mklink to make symlink for working with Windows 10 ?

Oh no, what I actually meant was that it works that way as well, as I said, 'later', so its not a requirement whatsoever and rather completely optional, just saves me a hefty amount of space in c drive.



> @Ansh4011 And can you please tell me which DLL version you are using for patching ?

[20230119](https://github.com/cinit/WSAPatch/releases/tag/r2023.01.19)

**Comment by YT-Advanced** [comment]
@Ansh4011 Wait what. Nothing different between your way with my patch. Can you test with this build (It have auto patch, so no need to patch DLL mannually)
https://github.com/YT-Advanced/WSA-Script/releases/latest

**Comment by Ansh4011** [comment]
> @Ansh4011 Wait what. Nothing different between your way with my patch. Can you test with this build (It have auto patch, so no need to patch DLL mannually) https://github.com/YT-Advanced/WSA-Script/releases/latest

Was about to install, but just checked the patch files are not present there neither is `appxmanifest.xml` patched.

**Comment by YT-Advanced** [comment]
@Ansh4011 Haha, I have added patcher to powershell script, just install and all of them will be patched, include DLLs and appxmanifest

**Comment by Ansh4011** [comment]
@YT-Advanced 
![image](https://github.com/cinit/WSAPatch/assets/84930340/a459ab73-1e25-4322-9516-d92ca3006419)

**Comment by Ansh4011** [comment]
> 

Oh wait browser didn't refresh lol, that's smart haha. Will try in a while, in class rn.

**Comment by YT-Advanced** [comment]
@Ansh4011 You can check these line 
![image](https://github.com/cinit/WSAPatch/assets/70064328/c5ebf3da-f2da-4221-88b7-9bd19ec999e6)

**Comment by Ansh4011** [comment]
> @Ansh4011 You can check these line ![image](https://user-images.githubusercontent.com/70064328/244623062-c5ebf3da-f2da-4221-88b7-9bd19ec999e6.png)

@YT-Advanced Yea I tried `v2304`, doesn't seem to work, tried your repo and wsabuilds too. But then out of curiosity I ran `v2305`, the pre-release from your repo, modified `install.sh` for 21h2 and it worked, worked smooth af. Seems like the issue was only with `v2304`.

**Comment by YT-Advanced** [comment]
@Ansh4011 I can't understand the line below. You mean v2305 from my repos worked smooth without any modify from you ?
>  the pre-release from your repo, modified install.sh for 21h2 and it worked

**Comment by Ansh4011** [comment]
> @Ansh4011 I can't understand the line below. You mean v2305 from my repos worked smooth without any modify from you ?
> 
> > the pre-release from your repo, modified install.sh for 21h2 and it worked

I was referring to this `22h2`, bcz I run `21h2` so I had to edit it to make it work.
![image](https://github.com/cinit/WSAPatch/assets/84930340/8bea8745-2c88-4f75-b4c1-293cfcc544d1)

**Comment by YT-Advanced** [comment]
Oh, thanks. I will modify it :)))
P/s: Finished building:
https://github.com/YT-Advanced/WSA-Script/releases/tag/WSA-Insider-Version

**Comment by ZzZombo** [comment]
So does this mean we can install the latest version on Windows 10 as is or not? Any step-by-step example otherwise?

**Comment by YT-Advanced** [comment]
> So does this mean we can install the latest version on Windows 10 as is or not? Any step-by-step example otherwise?

I think we can.

**Comment by Ansh4011** [comment]
> Oh, thanks. I will modify it :)))

Welcome 😄

**Comment by Ansh4011** [comment]
> So does this mean we can install the latest version on Windows 10 as is or not? Any step-by-step example otherwise?

https://github.com/cinit/WSAPatch/issues/33#issuecomment-1583364007

**Comment by Ansh4011** [comment]
> P/s: I'm building with new Powershell script
https://github.com/YT-Advanced/WSA-Script/actions/runs/5217274339

@YT-Advanced Good job man! Need me to test it? Can do today, cause I'll be busier tmrw onwards.

**Comment by YT-Advanced** [comment]
> @YT-Advanced Good job man! Need me to test it? Can do today, cause I'll be busier tmrw onwards.

@Ansh4011 Yes, you can test it via this link (Better than WSABuilds):
https://github.com/YT-Advanced/WSA-Script/releases/tag/WSA-Insider-Version

**Comment by MustardChef** [comment]
You can get WSA Builds v2305 for Windows 10 from here: https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2305.40000.3.0

**Comment by emanuel242026-cpu** [comment]
> [@cinit](https://github.com/cinit)WSAPatch ya no funciona con WSA v2304.40000.3.0 y versiones superiores, y genera el siguiente error: ¿Puede echar un vistazo al problema en cuestión? ![image](https://github.com/cinit/WSAPatch/assets/68516357/040761b1-94d1-4054-8454-7462c8350e9f)
> 
> Muchas gracias, MustardChef
