### ISSUE TITLE
No Network in WSA v2211.40000.10.0 on 10.0.19045.2364

### ISSUE THREAD

**Issue by hidacow** [cinit/WSAPatch#6]
I tried the following:
`WSA_2211.40000.10.0_x64_Release-Nightly-with-magisk-a468fd94(25205)-canary-MindTheGapps-13.0-RemovedAmazon`
`WSA_2210.40000.7.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-12.1-RemovedAmazon`
on my Windows 10.0.19045.2364 Enterprise
At first I was not able to run any app because the window exited immediately.
I found that this is a problem related to my GPU, you must select the GPU to get the apps starting.
![image](https://user-images.githubusercontent.com/68262945/208382161-e8207c97-a51d-4629-bfa7-63e47e6bec78.png)
However, the WSA cannot connect to Google (This shouldn't be a problem for my network as my WSL Ubuntu can connect to Google) and the network seems failing
In addition, I cannot connect to the adb as no ports are open.
![image](https://user-images.githubusercontent.com/68262945/208384600-ea392549-ed56-47cd-857c-8afe3d6f767d.png)
There's no program listening on localhost:58526 either.
Similar to #5 , I cannot turn on the Wireless Debug too.
![image](https://user-images.githubusercontent.com/68262945/208385156-354baa8d-3fa0-43b2-b32b-f8eda7719def.png)
The Wifi settings look like this
![image](https://user-images.githubusercontent.com/68262945/208386378-1719f357-e29d-4e21-92f2-42ca67374e0d.png)
![image](https://user-images.githubusercontent.com/68262945/208386828-4718d005-2696-46f5-87c7-73696f63e635.png)
I also tried my Windows Firewall settings but it did not work.

**Comment by hidacow** [comment]
I made a setting mistake and the WSA can connect to Internet now.
I also found out why my adb is not available and a solution, as described in my comment in #5

**Comment by ticowise** [comment]
> Я допустил ошибку настройки, и WSA теперь может подключаться к Интернету.Я также выяснил, почему мой adb недоступен, и нашел решение, как описано в моем комментарии в [# 5](https://github.com/cinit/WSAPatch/issues/5)

what did you do to make it work i have the same problem

**Comment by hidacow** [comment]
Can you connect to ADB? If not, try https://github.com/cinit/WSAPatch/issues/5#issuecomment-1357768098.
If the issue is related to port binding problem, you may let another application bind to the 58526 port and see the error msg.
There may be other issues causing the ADB not working, I may not know the solution.
I thought my Network problem was related to UWP Loopback problem and has nothing to do with this Patch.
Maybe you should check the network settings carefully especially if you are using some kind of proxy to connect to the internet.
